[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F401RETx --connect-under-reset"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"

[profile.release]
lto = true
opt-level = "s"
incremental = false
codegen-units = 1
debug = true


